### ISSUE TITLE
Merge into activeadmin-globalize

### ISSUE THREAD

**Issue by halilim** [fabn/activeadmin-globalize#11]
It looks like this branch is kind of maintained. What about merging all/some changes into the original [activeadmin-globalize](https://github.com/unmantained-activeadmin-plugins/activeadmin-globalize) and maintaining it instead of this fork?

**Comment by fabn** [comment]
I already tried to do that, see https://github.com/unmantained-activeadmin-plugins/activeadmin-globalize/pull/38

Former maintainer never gave any feedback. Also in his [latest commit](https://github.com/unmantained-activeadmin-plugins/activeadmin-globalize/commit/856c4f13007bfaac7d09e074ea69114bc9123fb4) he clearly states the he won't maintain this plugin anymore so this will remain a fork.

You can use this gem, it's tested with latest AA and rails 4.2 and its working. I'll try to keep it updated when newer version of dependencies are released.

The only notable issue is #4 you can read the whole issue or simply refer to my note in README.

**Comment by halilim** [comment]
Oh, sorry, I forgot to check the closed issues there. So it looks like @stefanoverna has completely abandoned it.

Yeah, I'm successfully using this in a project, thanks for the maintenance work :+1:
