### ISSUE TITLE
activeadmin 9132da6 form_buffer removed

### ISSUE THREAD

**Issue by ghost** [fabn/activeadmin-globalize#3]
In the current activeadmin master (9132da6) "form_buffer" in lib/active_admin/views/components/active_admin_form.rb has been removed. (raise "'form_buffers' has been removed from ActiveAdmin::FormBuilder, please read https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md for details.") Therefore, activeadmin-globalize "f.translated_inputs" function does not work anymore.

**Comment by besi** [comment]
Please note there is now a [1.0.0.pre1](v1.0.0.pre1) release of Active Admin

**Comment by fabn** [comment]
Yes I saw that. I'll try to make this gem compatible with AA released version as soon as I can (I'll need that too).
