### ISSUE TITLE
Rails 4.2 compatability

### ISSUE THREAD

**Issue by besi** [fabn/activeadmin-globalize#6]
I want to update my project from Rails 4.1 to Rails 4.2. 

The globalize Readme states:

> When using bundler put this in your Gemfile:
>
> ```ruby
> gem 'globalize', '~> 5.0.0'
> ```
> 
> To use the version of globalize for ActiveRecord 4.0 or 4.1, specify:
> 
> ```ruby
> gem 'globalize', '~> 4.0.3'
> ```

So I also updated the globalize gem from 4 to 5. However when I do this I get a dependency error:

```terminal
$ bundle update activeadmin-globalize globalize
Updating git://github.com/fabn/activeadmin-globalize.git
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "globalize":
  In Gemfile:
    activeadmin-globalize (~> 1.0.0.pre) ruby depends on
      globalize (~> 4.0) ruby

    globalize (5.0.0)
```

Is there generally a way to get `activeadmin-globalize` to work with rails 4.2

**Comment by fabn** [comment]
Not yet. I will work on this on the next few days and I will use a travis build matrix in specs to ensure it's working on all released rails versions.

**Comment by besi** [comment]
:+1:  Thanks for the heads up

**Comment by micred** [comment]
Hi @fabn are there any progress in Rails 4.2 compatibility? I will happy to test a dev branch if you like.
Thank you

**Comment by NickClark** [comment]
Status update on the Rails 4.2 support?

**Comment by fabn** [comment]
I relaxed dependencies to work with rails 4.2. Now you should be able to install this gem in rails 4.2 using the develop branch.

**Comment by besi** [comment]
@fabn Is Rails 5 already on the roadmap?

**Comment by fabn** [comment]
@besi not yet. I'm pretty busy with work in this period and I don't know when I'll be able to handle that.

Meanwhile if you want to sketch a PR it would be very welcome 😉

**Comment by besi** [comment]
Actually the `develop` branch seems to be working fine:

![screen shot 2017-10-02 at 13 54 21](https://user-images.githubusercontent.com/160412/31076159-3ada2368-a779-11e7-8ae3-a390ce3ccb10.png)

![screen shot 2017-10-02 at 13 53 52](https://user-images.githubusercontent.com/160412/31076165-3d72efce-a779-11e7-9971-1e3a1ced4d10.png)


This is an excerpt from my Gemfile:

I'm using ruby 2.4.1.p111

```ruby
gem 'rails', '~> 5.1.4'
gem 'activeadmin'
gem 'activeadmin-sortable'
gem 'globalize', git: 'https://github.com/globalize/globalize', branch: 'master'
gem 'activemodel-serializers-xml'
gem 'activeadmin-globalize', github: 'fabn/activeadmin-globalize', branch: 'develop'
gem 'globalize-versioning', github: 'besi/globalize-versioning', branch: 'patch-1'
```

<sub>Sidenote: I am using the globalize-versioning which isn't fully compatible yet. See this issue <https://github.com/globalize/globalize-versioning/pull/14></sub>
