### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by XBeg9** [fabn/activeadmin-globalize#7]
I have latest code from `develop` branch.

Here is workflow:
1) Create model (+migration)
2) Add translates methods to model
3) Add translation migration for model
run `rake db:migrate` and you will get such errors:

`activeadmin-28e8a8f36640/lib/active_admin/error.rb:43:in rescue in capture': Your file, app/models/hotel.rb (line 5), caused a database error while Active Admin was loading. This is most common when your database is missing or doesn't have the latest migrations applied. To prevent this error, move the code to a place where it will only be run when a page is rendered. One solution can be, to wrap the query in a Proc.Original error message: PG::UndefinedTable: ERROR:  relation "hotels" does not exist LINE 5:                WHERE a.attrelid = '"hotels"'::regclass`
on line 5 we have:
`translates :description, :room_services_description`

If you remove this line from model, run migration this will also fail because next migration needs `create_translation_table!` method.

I think it's really critical issue.

**Comment by fabn** [comment]
Are you sure this issue is caused by this gem? `translates` AR method comes from [globalize](https://github.com/globalize/globalize) gem.

With this gem you're supposed to use 

```ruby
active_admin_translates description, :room_services_description
```

Instead of 
```ruby
translates :description, :room_services_description
```

**Comment by fabn** [comment]
Reopen it if you still having issues
