### ISSUE TITLE
Attribute "locale" not sent to controller, even if in permitted params

### ISSUE THREAD

**Issue by micred** [fabn/activeadmin-globalize#8]
Hi, with latest revision it looks like that locale parameter is not included in the update/create actions.

![schermata 2015-04-27 alle 12 40 50](https://cloud.githubusercontent.com/assets/511434/7346250/afb4a1a4-ecdc-11e4-9e2b-f7911258b738.png)

Am I wrong?

#show is ok, it preload the correct translations.

**Comment by fabn** [comment]
Do you have `locale` listed as allowed param in `permit_params` e.g. something like this

```ruby
  permit_params do
    allowed_params = [:email, :website, :blog]
    allowed_params.push({translations_attributes: [:id, :locale, :first_name, :last_name, :_destroy]})
  end
```

**Comment by micred** [comment]
Yes, I do.
Maybe it's related to #4 : 
if I explicitly add `t.input :locale, as: :hidden` to translated_inputs block, it render this hidden :locale field but not the localized :name input anymore.

```
    f.translated_inputs "Translated fields", switch_locale: true do |t|
      t.input :name
      t.input :locale, as: :hidden
    end
```

Similarly if I switch the order, it renders the :name without the :locale, so it renders always the last one. Any idea/workaround?!

**Comment by fabn** [comment]
Could you please wrap your `f.translated_inputs` into an `f.inputs` block and tell me if it solves the issue?

```ruby
    f.inputs 'Whatever title' do
      f.translated_inputs "Translated fields", switch_locale: true do |t|
        t.input :name
      end
    end
```

**Comment by micred** [comment]
Yep that block is needed, but it was not the problem.
I lock activeadmin to https://github.com/activeadmin/activeadmin/commit/930d34c as you suggested on #5 and now it works!
I think because that revision is using formtastic 2.3 while recent activeadmin revisions use formtastic 3.1.

**Comment by fabn** [comment]
See followup in #4. Thanks.
