### ISSUE TITLE
No destroy checkbox shown when using only localized attributes

### ISSUE THREAD

**Issue by micred** [fabn/activeadmin-globalize#9]
Using the following code I don't get the _destroy checkbox on the has_many (even if allow_destroy: true).
```
    f.inputs '' do
      f.has_many :adornments, allow_destroy: true do |nested_resource|
        nested_resource.translated_inputs '', switch_locale: true do |l|
          l.input :name
        end
      end
    end
```

If I put a non-localized attribute the _destroy checkbox appears.

Using:
 * activeadmin (1.0.0.pre 930d34c)
 * activeadmin-globalize (1.0.0.pre fd38348)

**Comment by micred** [comment]
It works wrapping `translated_inputs` in a `inputs` block.
I may suggest adding it to the example in the documentation.

**Comment by fabn** [comment]
Good to know, I'll try to fix the syntax to work without nesting and to release a working version this weekend.

**Comment by fabn** [comment]
I worked on this and this issue is the same as #4. Going to close this, follow #4 and activeadmin/activeadmin#4024 for resolution.
